dist: trusty
language: elixir
elixir: 1.9.4
otp_release: 22.0

addons:
  postgresql: 9.6

jobs:
  include:
    - stage: test
      script:
        - mix test --include integration
        - sudo cat /var/log/postgresql/postgresql-9.6-main.log
        - mix run priv/repo/seeds.exs

    - stage: hex
      env: HEX_VERSION=master
      before_script:
        - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
        - cd hex && mix deps.get && cd ..
      script:
        - cd hex && mix test --include integration && cd ..
        - sudo cat /var/log/postgresql/postgresql-9.6-main.log

    - env: HEX_VERSION=v0.20
      before_script:
        - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
        - cd hex && mix deps.get && cd ..
      script:
        - cd hex && mix test --include integration && cd ..
        - sudo cat /var/log/postgresql/postgresql-9.6-main.log

    - env: HEX_VERSION=v0.19
      before_script:
        - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
        - cd hex && mix deps.get && cd ..
      script:
        - cd hex && mix test --include integration && cd ..
        - sudo cat /var/log/postgresql/postgresql-9.6-main.log

    - env: HEX_VERSION=v0.18
      before_script:
        - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
        - cd hex && mix deps.get && cd ..
      script:
        - cd hex && mix test --include integration && cd ..
        - sudo cat /var/log/postgresql/postgresql-9.6-main.log

env:
  global:
    - MIX_ENV=test
    - HEXPM_PATH=..

notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
